### ISSUE TITLE
Greška validacije

### ISSUE THREAD

**Issue by lejlasolak** [SoftverInzenjeringETFSA/2018_SpendingTracker#1]
Komponenta: SpendingTracker/NoviRacun
commit ID: 0acb520570ae64570af262a415a1320129799dae
Opis problema: Validacija novog računa ne radi: ne validira se da li postoji račun sa istim nazivom ni da li korisnik već ima 10 kreiranih računa.
Koraci za reproduciranje problema: 
1. Pokrenuti aplikaciju "Spending tracker" prema uputstvu na linku 
https://github.com/SoftverInzenjeringETFSA/2018_SpendingTracker/blob/master/README.md 
2. Unijeti svoje podatke za prijavu: email i password
3. Kliknuti na dugme "PRIJAVI SE"
4. Kliknuti na dugme "NOVI RAČUN"
5. Unijeti "Racun" u polje "Naziv"
6. Unijeti "5000" u polje "Trenutni iznos"
7. Kliknuti na dugme "UNESI"
8. Vratiti se na prethodnu formu i ponoviti korake 5-8

Dobijeni rezultat: Pojavi se poruka "Uspješno dodan novi račun - Racun"
Očekivani rezultat: Očekuje se poruka o grešci da račun sa istim nazivom već postoji, jer je tako definisano u uslovima validnosti
![unos racuna](https://user-images.githubusercontent.com/26254824/41298969-b8de7664-6e62-11e8-80c7-f3b7607c8163.jpg)
![poruka o unosu](https://user-images.githubusercontent.com/26254824/41298985-c15122f6-6e62-11e8-9702-5000f5f07fc8.jpg)

**Comment by hannabojadzic** [comment]
Implementacija zahtjeva previše promjena, te tim nema dovoljno vremena da se iste provedu.
